### ISSUE TITLE
Dynamic partials not working

### ISSUE THREAD

**Issue by ssegal100** [linkedin/dustjs#691] opened 2015-08-07 11:36 UTC
When I include a partial it works fine, but when I try and make the name of the partial template dynamic
{>"{templateID}"/}, I get an error like this:
err = Error: Template Not Found: function i(e,i){return e.reference(i.get(["templateID"],!1),i,"h")}

templateID is part of the context and as a test I was able to retrieve it just by using this: {templateID}.
I'm using this on the client side only. Is it available or is it just server side functionality?
Thanks.

**Comment by prashn64** [comment] 2015-08-07 17:53
can you try {>"{templateID|s}"/}

I think the html encoding is screwing it up.

**Comment by sethkinast** [comment] 2015-08-07 18:06
Can you show us the actual context you are rendering with? We have tests around this use case so something is off. Are you using AMD loading or a custom `dust.onLoad` function?

**Comment by ssegal100** [comment] 2015-08-07 20:03
Thanks for the quick reply..
prashn64 - I just tried to add "|s" but i received a similar error:
 Template Not Found: function a(e,t){return e.reference(t.get(["templateID"],!1),t,"h",["s"])}

sethkinast - For simplicity if I remove the non-relevant data from the context, the context is 
{"templateID": "highlightPanel"}
"highlightPanel" is a precompiled template.

>>Are you using AMD loading or a custom dust.onLoad function?
I'm doing neither so this might be the problem. This is browser side only and the templates are precompiled. They are registered and I'm able to use them with the "dust.render" function. 
It sounds like I might have to load them manually, is that the case? if so what would be the recommended way to do this? 

As a test I tried dust.render("highlightPanel, data, fn..) prior to the actual render with the partial. I thought maybe this would load it into the cache. The first render, dust.render("highlightPanel, data, fn..), worked fine but the second one (with the partial) still failed in the same way.
Your help is appreciated.

Thanks for your help.

**Comment by sethkinast** [comment] 2015-08-07 20:09
If they are already registered this should just work. Let me try to
reproduce.

On Fri, Aug 7, 2015 at 1:03 PM, ssegal100 <notifications@github.com> wrote:

> Thanks for the quick reply..
> prashn64 - I just tried to add "|s" but i received a similar error:
> Template Not Found: function a(e,t){return
> e.reference(t.get(["templateID"],!1),t,"h",["s"])}
>
> sethkinast - For simplicity if I remove the non-relevant data from the
> context, the context is
> {"templateID": "highlightPanel"}
> "highlightPanel" is a precompiled template.
>
> Are you using AMD loading or a custom dust.onLoad function?
> I'm doing neither so this might be the problem. This is browser side only
> and the templates are precompiled. They are registered and I'm able to use
> them with the "dust.render" function.
> It sounds like I might have to load them manually, is that the case? if so
> what would be the recommended way to do this?
>
> As a test I tried dust.render("highlightPanel, data, fn..) prior to the
> actual render with the partial. I thought maybe this would load it into the
> cache. The first render, dust.render("highlightPanel, data, fn..), worked
> fine but the second one (with the partial) still failed in the same way.
> Your help is appreciated.
>
> Thanks for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/issues/691#issuecomment-128819932>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by sethkinast** [comment] 2015-08-07 20:26
OK, I'll bet I know.

Are you assigning a full object to `dust.config` somewhere?

e.g. `dust.config = { foo: 'bar' }`

If so, try assigning properties one at a time:

```
dust.config.foo = 'bar';
dust.config.baz = 'bop';
```

**Comment by sethkinast** [comment] 2015-08-07 20:27
Or do you have `dust.config.cache = false`?

**Comment by sethkinast** [comment] 2015-08-07 20:35
Dust 2.7.0 didn't like it when you assigned a whole object to `dust.config`, but the issue was fixed in 2.7.1. The current version is 2.7.2, so I hope you're just still using 2.7.0 and an upgrade will fix you up :)

**Comment by ssegal100** [comment] 2015-08-07 20:57
Sorry, I'm not using dust.config anywhere. I'm also on 2.7.2.

**Comment by sethkinast** [comment] 2015-08-07 21:18
Disaster! I can't reproduce the issue with a simple example:

```
dust.loadSource(dust.compile('the panel woo!', 'highlightPanel'));
dust.renderSource('rendering a {templateID}: {>"{templateID}"/}', { templateID: 'highlightPanel' }, function(err, out) {
    console.log(out);
});
```

Does this example work for you if you drop it in? It just logs `rendering a highlightPanel: the panel woo!` to the console.

**Comment by sethkinast** [comment] 2015-08-07 21:18
Are you using `dustc` to compile your templates?

**Comment by ssegal100** [comment] 2015-08-07 21:34
It does work for me. I am using dustc. I will use your example with dustc. Thanks.

**Comment by sethkinast** [comment] 2015-08-07 21:38
This is like the most basic example, so now let's try to narrow down how your use case differs from this simple example.

Hmm, it looks like your template is minified. I wonder if your minifier is mangling the template such that dust can no longer recognize it as a Dust template function. Can you share more details about how your templates are compiled?

**Comment by sethkinast** [comment] 2015-08-07 21:49
Or maybe paste the two precompiled templates in question (in compiled form)

**Comment by ssegal100** [comment] 2015-08-07 21:54
I'm using dusterjs with the -w option to auto-compile whenever there is a change to  a template. I am creating separate compiled files.
I just ran a test by pre-compiling the included template:
'the panel woo!', 'highlightPanel2'
The compile function looks like this:
!function(){function t(t,e){return t.write("'the panel woo!'")}return dust.register("highlightPanel2",t),t}();

It worked.

I then compiled the calling template. Its compiled function looks like this:
!function(){function e(e,t){return e.write("rendering a ").reference(t.get(["templateID"],!1),t,"h").write(": ").partial(r,t,null)}function r(e,r){return e.reference(r.get(["templateID"],!1),r,"h")}return dust.register("basePanel2",e),e}();

When I ran this:
dust.render("basePanel2", { templateID: 'highlightPanel2' }, function (err, out) {
        console.log(out);
    });

It did not work.

**Comment by sethkinast** [comment] 2015-08-07 22:04
There we go. That's the issue.

The latest public version of duster is `0.3.2`. But that version uses dust 2.3 to compile.

The unreleased 0.3.3 uses new Dust, but it's not released yet.
https://github.com/lee-houghton/dusterjs/commit/7ac8d31cd37bd5a809a0aa57364c972336f42885

The old compiler is not backwards-compatible with the current Dust code.

You could use `dustc`, which also has watch functionality and split functionality. But I understand if duster is kind of integrated into your workflow already.

**Comment by sethkinast** [comment] 2015-08-07 22:04
http://www.dustjs.com/docs/dustc-api

**Comment by ssegal100** [comment] 2015-08-07 22:08
That's great news! Thanks so much for your help. I'll use dustc.

**Closed** 2015-08-07 22:11 UTC
